import Head from 'next/head';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create nextapp' />
			</Head>
			<h1>Main Page</h1>
		</div>
	);
}
